### ISSUE TITLE
Error: Cannot stringify arbitrary non-POJOs on Object that have a toJSON method

### ISSUE THREAD

**Issue by victor-perez** [Rich-Harris/devalue#15]
If you have for example this code, I would expect that the `toJSON` method will be called of the object but instead it throws a non-POJOs error.
```javascript
var devalue = require("devalue")
var { Map } = require('immutable');
console.log(devalue({
    test: new Map({a:1})
}))
```

**Comment by Rich-Harris** [comment]
The purpose of devalue is to create a string representation of objects in memory that has 100% fidelity — i.e., by evaluating the string, you get exactly the same structure as existing before serialization.

If it called `toJSON` methods, it would no longer provide that guarantee. It's therefore out of scope for this project, so I'll close this issue — thanks
