### ISSUE TITLE
Change from LIL License

### ISSUE THREAD

**Issue by tvthatsme** [Rich-Harris/devalue#21]
Hi Rich,

Would it be possible to change from LIL License to something more standard (maybe MIT)? My company requires packages to be of a certain license before they can be used and the LIL License is not on the approved list nor seems supported these days (even the website lillicense.org is down now).

Thanks for considering!

**Comment by Rich-Harris** [comment]
yeah — I was rooting for LIL but it died a death, and I've been gradually moving projects over to MIT (which is basically identical, save for a bit more ambiguity around patents). Released 2.0.0 with an MIT license
