### ISSUE TITLE
update example-link in description

### ISSUE THREAD

**Issue by ivanhofer** [Rich-Harris/devalue#40]
This link points to a repl with an older version of `devalue`. The example does not work and requires you to manually fix the `import` before beeing able to play around and see the results.

![image](https://user-images.githubusercontent.com/21335119/195258815-6955c740-c836-4cf4-8276-0eb3f7ab0201.png)

**Comment by davidrunger** [comment]
After changing the `import` statement, although that fixes the `import` error, the example still doesn't work as expected. It fails with this error:

```
devalue is not a function (dataundefined)
```

One must also change

```js
devalue(data)
```

in the demo code to

```js
devalue.uneval(data)
```

to see `devalue` actually working.

**Comment by Rich-Harris** [comment]
fixed, thanks!
